"""
Django settings for cmnt_flagger project.

Generated by 'django-admin startproject' using Django 4.2.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-26#o5_1z=r-ug8dl1g)22g@nlp$)1x_3%^e99xuuw)g9(mvpc3'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'youtube_flagger'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware'
]

ROOT_URLCONF = 'cmnt_flagger.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'cmnt_flagger.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'flagger',
#         'USER': 'root',
#         'PASSWORD': 'Harismaran369!',
#         'HOST': 'localhost',
#         'PORT': '3306'
#     }
# }



# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True



EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'paramsolutionsotp@gmail.com'
EMAIL_HOST_PASSWORD = 'lmukdngstebmywzd'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, '../youtube_flagger/static/')
SECRETS_DIR = os.path.join(BASE_DIR, 'static/youtube_flagger/')
FILTER_VARIABLE = os.path.join(BASE_DIR, '../youtube_flagger/Scripts/')



MEDIA_ROOT = os.path.join(BASE_DIR,'media')
MEDIA_URL = 'media/'

# settings.py

# Add the APScheduler job store (usually, for SQLite, but you can choose other stores)
# AP_SCHEDULER_JOBSTORES = {
#     'default': {
#         'type': 'sqlalchemy',
#         'url': 'sqlite:///apscheduler.sqlite3',
#     }
# }

# Define the scheduler to use the above job store
# AP_SCHEDULER = {
#     'apscheduler.job_defaults.coalesce': 'false',
#     'apscheduler.job_defaults.max_instances': '3',
#     'apscheduler.timezone': 'UTC',
# }

STRIPE_SECRET_KEY = 'sk_test_51KTzzrSFKCkaJrMjFzXo8Tk51KOBIRFBH3M8iiHKRaHz32klrQnGRztQP6oZpRh0GSsF2Ot6AgUUBpkAc9bkuwGs00jomQskFj'
# STRIPE_PUBLISHABLE_KEY = ''

PAYPAL_CLIENT_ID = 'AeeZ-s6h6NGsG6vN9gU5HcOPij73jgWE6Ne-Hq_g02dFdW8-VTo52DbddEZy0CLZ12HlEJ8CW10RUyll'
PAYPAL_SECRET_KEY = 'EC0aKjHnnzUcK_eoRwCGPMPoh-wo9CvN7Yss0J7wVQnpCEPjoyBfowODzs_E122xOSwynMWEUcsFiFZQ'
PAYPAL_MODE = 'sandbox'
# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
