# Generated by Django 4.2.2 on 2023-07-19 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_flagger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistration',
            name='user_client_cobaltdeck_json',
            field=models.FileField(default='', upload_to='users/cobaltdeckjson'),
        ),
        migrations.AddField(
            model_name='userregistration',
            name='user_client_secret_json',
            field=models.FileField(default='', upload_to='users/secretsjson'),
        ),
    ]
