# Generated by Django 4.2.2 on 2023-07-21 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_flagger', '0006_remove_userregistration_user_client_cobaltdeck_json'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userregistration',
            name='user_client_secret_json',
        ),
    ]
