# Generated by Django 4.2.2 on 2023-07-25 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_flagger', '0007_remove_userregistration_user_client_secret_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistration',
            name='user_client_secret_json',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
