# Generated by Django 4.2.2 on 2023-07-25 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_flagger', '0008_userregistration_user_client_secret_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistration',
            name='user_client_secret_json',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='user_email',
            field=models.EmailField(max_length=254, verbose_name='Enter Email'),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='user_name',
            field=models.CharField(max_length=50, verbose_name='Enter your Name'),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='user_password',
            field=models.CharField(max_length=100, verbose_name='Enter Password'),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='user_phone',
            field=models.CharField(max_length=13, verbose_name='Enter Phone Number'),
        ),
        migrations.AlterModelTable(
            name='userregistration',
            table='UserInfo',
        ),
    ]
