# Generated by Django 4.2.2 on 2023-07-25 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_flagger', '0009_alter_userregistration_user_client_secret_json_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistration',
            name='user_client_cobaltdeck_json',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
