# Generated by Django 4.2.2 on 2023-07-25 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_flagger', '0011_alter_userregistration_user_client_cobaltdeck_json'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userregistration',
            table=None,
        ),
    ]
