# Generated by Django 4.2.2 on 2023-07-26 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_flagger', '0013_userregistration_user_youtube_channel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistration',
            name='user_youtube_channel_id',
            field=models.CharField(max_length=50, verbose_name='Enter your Channel Id'),
        ),
    ]
