# Generated by Django 4.2.2 on 2023-08-11 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_flagger', '0016_rename_user_client_service_account_json_file_userregistration_user_client_cobaltdeck_json'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userregistration',
            old_name='user_client_cobaltdeck_json',
            new_name='user_client_service_account_json_file',
        ),
    ]
