# Generated by Django 4.2.2 on 2023-08-18 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_flagger', '0019_listofuserinvitedadvisors_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listofuserinvitedadvisors',
            name='user_email',
        ),
        migrations.RemoveField(
            model_name='userregistration',
            name='Advisor_id',
        ),
        migrations.AddField(
            model_name='listofuserinvitedadvisors',
            name='user_id',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='listofuserinvitedadvisors',
            name='invited_friends_email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
